# Batch log
logging.level.org.springframework.batch: debug


logging:
  level:
    root: info
    org:

      # SpringFramework Logging
      springframework: debug
      hibernate:
        type:
          descriptor:

            # DB Query Logging
            sql: debug



