spring.profiles: db
spring.profiles.include: db_mysql, db_oracle

spring:
  h2:
  console:
    enabled: true


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:

            # DB Query Logging
            sql: info