spring:
  batch:
    job:
      # Spring Batch가 실행 될 때 Program arguments로 job.name 값이 넘어오면 해당 값과 일치하는 Job만 실행
      # None으로 설정 하는 이유는 파라미터로 어떠한 값이 없는 경우 None을 설정하여 어떠한 배치도 실행하지 않게끔 하기 위한 설정
      names: ${job.name:None}

  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
#main:
#  web-application-type: none
