# Batch log
logging.level.org.springframework.batch: info


logging:
  pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
  level:
    root: info
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      # SpringFramework Logging
      springframework: info
        # jpa 쿼리를 로그 파일로 출력
        #      hibernate:
        #        SQL: debug
      # 로그 파라미터까지 확인
#        type: trace
