spring.profiles: local
spring:
  profiles:
    include: db, batch

# 서버 포트 설정
server:
  port: 8082

# 로그 설정
logging:
  level:
    org:
      springframework:
        batch: info

file:
  library: files/전국도서관표준데이터.csv
  area: files/법정동코드전체자료.txt
