# 해당 프로퍼티 파일 이름
spring.profiles: db_mysql

spring:
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # 프로젝트 처음 실행 할 때 sequence 테이블 만들어야 함
    generate-ddl: true
    # 쿼리 확인
#    show_sql: true
    properties:
      hibernate:
        # console에 출력 시 줄 바꾸기
#        format_sql: true
        ddl-auto: update # 스키마가 변경된 경우에만 실행
#        ddl-auto: none # 실행하지 않음
#       ddl-auto: create-drop # 어플리케이션이 구동되고 Session이 시작될때 drop -> create 이 실행되고, Session이 종료될때 (어플리케이션 종료) drop
#        ddl-auto: create # 어플리케이션이 구동되고 Session이 시작될때 drop -> create 이 실행
#       ddl-auto: validate # 변경여부 확인 후 출력, 어플리케이션은 종료

  # MySQL DataSource
  datasource:
    # Spring Batch Schema MySQL
    batch:
      jdbc-url: jdbc:mysql://localhost:3308/batch_db?useSSL=false
      username: seok
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      sql-script-encoding: UTF-8
