# 해당 프로퍼티 파일 이름

spring.profiles: db_mysql

spring:
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none # 실행하지 않음
    hibernate:
      naming:
        # 테이블 명 소문자로 쿼리 날려서 해당 DB에서 찾을 수 없는 문제로 인한 설정
        # https://stackoverflow.com/questions/28571848/spring-boot-jpa-insert-in-table-with-uppercase-name-with-hibernate
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # MySQL DataSource
  datasource:
    # Spring Batch Schema MySQL
    url: jdbc:mysql://localhost:3308/batch_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: seok
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


